### ISSUE TITLE
variable time-intervals in "per country" plot

### ISSUE THREAD

**Issue by TYMichaelsen** [hodcroftlab/covariants#109] opened 2021-02-24 09:21 UTC
Hi,

When looking at the Danish frequency plot of variants here https://covariants.org/per-country I noticed that the intervals varies in size? so for instance 2020-12-21 to 2020-12-28 is one week and 2020-12-07 to 2020-12-21 is two weeks? I hope it's a mistake! :)

On that note, could the dates be more informative? So for example indicate which ISO-standard week they cover instead of showing a specific date?

Best,
Thomas

**Comment by emmahodcroft** [comment] 2021-02-24 09:47
Hi @TYMichaelsen Thanks for spotting this. From checking the rest of the data, it seems this one date period (2020-12-21 to 2020-12-28) is not following the pattern we intend! I think this might be an edge-case about how we divide up into the two-week periods. I'll investigate this and see if we can get it fixed!

Regarding the dates/ISO week - I decided to go with the 'actual dates' as for people who don't work with ISO weeks regularly they're quite confusing and not intuitive, but I agree that for those who are familiar with ISO weeks this might make more sense. A good option might be to have a toggle-switch at the top of the page so that users can switch between the two and use whichever is more useful for them! 

Would you mind making an issue for that, and we can see if we can get that implemented?

**Comment by emmahodcroft** [comment] 2021-02-25 11:47
Hi @TYMichaelsen - I tracked this down to the change in year from 2020 to 2021. Here's how this is done in `datetime` converting from ISO week to date:

```
(2020, 50)  (2020, 12, 7, 0, 0)
(2020, 52)  (2020, 12, 21, 0, 0)
(2021,  0)  (2020, 12, 28, 0, 0)
(2021,  2)  (2021, 1, 11, 0, 0)
```

The issue seems to be that essentially there has to be a little fiddling with ISO weeks, because the ISO weeks don't necessarily divide so evenly into the year. (I don't work with ISO week dates myself so this is all a bit new to me.)

As far as I could tell from researching, there doesn't seem to be an easy fix for this for 2-week increments. I think the best solution might be to just accept that this one point will be 'off' (but it should not repeat until perhaps New Year 2022), and work to enable a toggle to switch between dates & ISO weeks so that this is easier for users to investigate (and hopefully, if they are a bit familiar with ISO weeks, to see the cause in the end-of-year!). 

However, if you're more familiar with ISO weeks and know of ways this is handled by others, I'd certainly appreciate any thoughts you might have!

**Comment by corneliusroemer** [comment] 2021-03-31 12:25
I'm sure this can be fixed. Which way are you converting? Why do you use calendar weeks in the first place? Is that how you decide to bin or is it externally imposed? Maybe if you point to the code I can have a look.

**Comment by emmahodcroft** [comment] 2021-03-31 12:49
In the code everything is processed by ISO-week (or ISO-2-week, which is the problem here - that's not a 'real' format, I'm just squishing two ISO weeks together). I then convert this to dates to display because for many people (including myself) this is more intuitive. 

Examples:
Warning: the code below is a bit of a hot mess. Apologies. I'll tidy it up someday, but the pandemic never leaves me enough time to get to it....
You can see how things are gathered up by week [here](https://github.com/hodcroftlab/covariants/blob/master/scripts/allClusterDynamics_faster.py#L630)
And by two-week [here](https://github.com/hodcroftlab/covariants/blob/master/scripts/allClusterDynamics_faster.py#L649)
You can see how ISO weeks are converted to dates [here](https://github.com/hodcroftlab/covariants/blob/master/scripts/helpers.py#L42)

The thing is, ISO weeks themselves have to hack a bit to fit into the 52week year (which starts/ends with different day of the week). There's ways this is handled standardly, but they don't work very well when you split things into 2 weeks, as this likely overlaps the tricky 'near year period'. 

We use ISO week because it's a standard data format that makes it very easy to bin things by week without having to do other complicated calculations about what a 'week' is (will we ever invent a metric system for calendar-time?). Week is also a very standard time period for epi work, which is why it would be handy to have a toggle to move between the two. Lots of epi people can parse ISO week better than dates. (Not me.)

**Comment by emmahodcroft** [comment] 2021-03-31 12:51
I think that even if the two-week problem remains (which should only ever happen once a year, around the end/start of the year), adding a toggle to switch to ISO-week would mean it would also (hopefully) be clear why the inconsistency - to start the new year on week 1, we had to truncate a 2-week period. I could export ISO week to the JSON which is eventually used to render plots, that might be easiest - but have never gotten around to it.

**Comment by emmahodcroft** [comment] 2024-12-04 09:08
@AdvancedCodingMonkey At least from mousing over the dates specified at the top of this PR, the dates that Thomas spotted don't seem to exist anymore, neither does the 'end of year jitter'. So I think I'm correct in saying that Moira fixed this and this isn't an issue anymore!

**Comment by AdvancedCodingMonkey** [comment] 2024-12-04 09:30
Also mentioned as fixed in the [changelog](https://github.com/hodcroftlab/covariants/blob/master/CHANGELOG.md#2022-07-22), closing the issue.

**Closed by AdvancedCodingMonkey** 2024-12-04 09:30 UTC
Labels: bug, scope: web, needs triage, unfinished
